earphones:
    path:     /
    defaults: { _controller: "CatalogBundle:Earphone:index" }

earphone_show:
    path:     /{id}/show
    defaults: { _controller: "CatalogBundle:Earphone:show" }

earphone_new:
    path:     /new
    defaults: { _controller: "CatalogBundle:Earphone:new" }

earphone_create:
    path:     /create
    defaults: { _controller: "CatalogBundle:Earphone:create" }
    requirements: { _method: post }

earphone_edit:
    path:     /{id}/edit
    defaults: { _controller: "CatalogBundle:Earphone:edit" }

earphone_update:
    path:     /{id}/update
    defaults: { _controller: "CatalogBundle:Earphone:update" }
    requirements: { _method: post|put }

earphone_delete:
    path:     /{id}/delete
    defaults: { _controller: "CatalogBundle:Earphone:delete" }
    requirements: { _method: post|delete }
