keyboards:
    path:     /
    defaults: { _controller: "CatalogBundle:Keyboard:index" }

keyboard_show:
    path:     /{id}/show
    defaults: { _controller: "CatalogBundle:Keyboard:show" }

keyboard_new:
    path:     /new
    defaults: { _controller: "CatalogBundle:Keyboard:new" }

keyboard_create:
    path:     /create
    defaults: { _controller: "CatalogBundle:Keyboard:create" }
    requirements: { _method: post }

keyboard_edit:
    path:     /{id}/edit
    defaults: { _controller: "CatalogBundle:Keyboard:edit" }

keyboard_update:
    path:     /{id}/update
    defaults: { _controller: "CatalogBundle:Keyboard:update" }
    requirements: { _method: post|put }

keyboard_delete:
    path:     /{id}/delete
    defaults: { _controller: "CatalogBundle:Keyboard:delete" }
    requirements: { _method: post|delete }
