news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: NewsBundle:Secured:login }
    
login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
