news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /
NewsBundle_news:
    resource: "@NewsBundle/Resources/config/routing/news.yml"
    prefix:   /news
    
NewsBundle_category:
        resource: "@NewsBundle/Resources/config/routing/category.yml"
        prefix:   /category