security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ITR\NewsBundle\Entity\User: sha1

    role_hierarchy:
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN:       [ROLE_MANAGER, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
         main:
            entity:
                class: ITR\NewsBundle\Entity\User 
                property: user_email
    
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        demo_login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        demo_secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _demo_security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/passwordrecovery, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/updatepassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mainpage/, roles: ROLE_USER}
        - { path: ^/catalog/, roles: ROLE_USER}
        - { path: ^/printer/, roles: ROLE_USER}
        - { path: ^/admin, roles: ROLE_MANAGER}
        - { path: ^/admin/news, roles: ROLE_MANAGER}
        - { path: ^/admin/category, roles: ROLE_MANAGER}
        - { path: ^/admin/user, roles: ROLE_MANAGER}
   
    #access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }