ITR\CatalogBundle\Entity\Earphone:
    type: entity
    table: null
    repositoryClass: ITR\CatalogBundle\Entity\EarphoneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
