ITR\CatalogBundle\Entity\GoodsSellers:
    type: entity
    table: null
    repositoryClass: ITR\CatalogBundle\Entity\GoodsSellersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        price:
            type: integer
            options:
                unsigned: true
                default: 0
        quantity:
            type: integer
            options:
                unsigned: true
                default: 0
    manyToOne:
            goods_id:
                targetEntity: Goods
                inversedBy: sellers
                joinColumn:
                    name: goods_id
                    referencedColumnName: id
            seller_id:
                targetEntity: Seller
                inversedBy: goods
                joinColumn:
                     name: seller_id
                     referencedColumnName: id
    lifecycleCallbacks: {  }
