ITR\CatalogBundle\Entity\GoodsCategory:
    type: entity
    table: null
    repositoryClass: ITR\CatalogBundle\Entity\GoodsCategoryRepository
    indexes:
        categoryName_index:
            columns: [ categoryName ]

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryName:
            type: string
            length: 255
        tableName:
            type: string
            length: 255
            nullable: true
    oneToMany:
        goods:
            targetEntity: Goods
            mappedBy: goods_category
        children:
            targetEntity: GoodsCategory
            mappedBy: parent

    manyToOne:
        parent:
            targetEntity: GoodsCategory
            inversedBy: children

    lifecycleCallbacks: {  }
