ITR\CatalogBundle\Entity\Printer:
    type: entity
    table: null
    repositoryClass: ITR\CatalogBundle\Entity\PrinterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        scanner:
            type: boolean
            nullable: true
            options:
                default: 0
        fax:
            type: boolean
            nullable: true
            options:
                default: 0
        printType:
            type: string
            length: 255
            column: print_type
            nullable: true
        format:
            type: string
            length: 100
            columnt: print_format
            nullable: true
        speed:
            type: string
            length: 100
            column: speed
            nullable: true
        weight:
            type: float
            column: weight
            nullable: true
    oneToMany:
        goods_id:
            targetEntity: Goods
            mappedBy: goods_id
    lifecycleCallbacks: {  }
