ITR\CatalogBundle\Entity\Rating:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mark:
            type: integer
    manyToOne:
           user_id:
                targetEntity: ITR\NewsBundle\Entity\User
                inversedBy: rating
                joinColumn:
                    name: user_id
                    referencedColumnName: id
           goods_id:
                 targetEntity: Goods
                 inversedBy: rating
                 joinColumn:
                     name: goods_id
                     referencedColumnName: id
    lifecycleCallbacks: {  }
