ITR\CatalogBundle\Entity\Seller:
    type: entity
    table: null
    repositoryClass: ITR\CatalogBundle\Entity\SellerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: string
            length: 255
            nullable: true
        number:
            type: string
            length: 255
        email:
            type: string
            length: '30'
            nullable: true
        skype:
            type: string
            length: '30'
            nullable: true
        schedule:
            type: string
            length: 255
        description:
            type: string
            length: '2048'
    oneToMany:
           goods:
              targetEntity: GoodsSellers
              mappedBy: seller_id
           phone:
              targetEntity: Phone
              mappedBy: seller_id
    lifecycleCallbacks: {  }
