ITR\CatalogBundle\Entity\Seller:
    type: entity
    table: null
    repositoryClass: ITR\CatalogBundle\Entity\SellerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: string
            length: 255
        email:
            type: string
            length: '30'
        skype:
            type: string
            length: '30'
        schedule:
            type: string
            length: 255
        description:
            type: string
            length: '2048'
    lifecycleCallbacks: {  }
