_welcome:
    path:     /
    defaults: { _controller: NewsBundle:Welcome:index }

hello:
    path:     /hello
    defaults: { _controller: NewsBundle:Default:index }
    
NewsBundle_news:
        resource: "@NewsBundle/Resources/config/routing/news.yml"
        prefix:   /news
        
NewsBundle_category:
    resource: "@NewsBundle/Resources/config/routing/category.yml"
    prefix:   /category
    
NewsBundle_user:
        resource: "@NewsBundle/Resources/config/routing/user.yml"
        prefix:   /user
_login:
    path:     /login
    defaults: { _controller: NewsBundle:Secured:login }

NewsBundle_dispatch:
        resource: "@NewsBundle/Resources/config/routing/dispatch.yml"
        prefix:   /dispatch
        
_registration:
    path:     /registration
    defaults: { _controller: NewsBundle:Registration:index }
