parameters:
#    news.example.class: ITR\NewsBundle\Example

services:
#    news.example:
#        class: %news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    itr.news.menu.voter.request:
        class: ITR\NewsBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
    itr_news.menu_builder:
        class: ITR\NewsBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    itr_news.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: itr_news.menu_builder
        factory_method: createMainMenu
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu