parameters:
#    news.example.class: ITR\NewsBundle\Example

services:
#    news.example:
#        class: %news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    itr.news.menu.voter.request:
        class: ITR\NewsBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }