ITR\NewsBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user_email]
            message: "not.unique.email"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user_name]
            message: "not.unique.username"
    properties:
        user_password:
            - NotBlank: { message: "not.blank.password" }
    properties:
        user_email:
            -NotBlank: { message: "not.blank.email" }
            
ITR\NewsBundle\Entity\Category: 
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [category_name] 
            message: "not.unique.category"
    properties:
        category_name:
            - NotBlank: { message: "not.blank.category" }
    