<?php

namespace ITR\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EarphoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EarphoneRepository extends EntityRepository
{
}
