<?php

namespace ITR\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoodsSellersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsSellersRepository extends EntityRepository
{
}
