<?php

namespace ITR\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsCategoryRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM CatalogBundle:GoodsCategory c ORDER BY c.category_name ASC')
            ->getResult();
    }


    public function findAllParents()
    {
        $q = $this
            ->createQueryBuilder('c')
           ->where('c.parent IS NULL')
            ->orderBy('c.categoryName', 'ASC')
            ->getQuery();
            $categories= $q->getResult();

        return $categories;
    }
    public function findAllChildren()
    {
        $q = $this
            ->createQueryBuilder('c')
            ->where('c.parent IS not NULL')
            ->orderBy('c.categoryName', 'ASC')
            ->getQuery();
        $categories= $q->getResult();

        return $categories;
    }
}
