<?php

namespace ITR\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeyboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyboardRepository extends EntityRepository
{
}
