catalog_homepage:
    path:     /catalog
    defaults: { _controller: CatalogBundle:Catalog:show }
catalog_category:
    path:     /catalog/{category}
    defaults: { _controller: CatalogBundle:Catalog:showGoods }
CatalogBundle_admin_seller:
    resource: "@CatalogBundle/Resources/config/routing/seller.yml"
    prefix:   /admin/seller

