parameters:
#    catalog.example.class: ITR\CatalogBundle\Example

services:
#    catalog.example:
#        class: %catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
