category:
    path:     admin/
    defaults: { _controller: "NewsBundle:Category:index" }

category_show:
    path:     admin/{id}/show
    defaults: { _controller: "NewsBundle:Category:show" }

category_new:
    path:     admin/new
    defaults: { _controller: "NewsBundle:Category:new" }

category_create:
    path:     admin/create
    defaults: { _controller: "NewsBundle:Category:create" }
    requirements: { _method: post|get }

category_edit:
    path:     admin/{id}/edit
    defaults: { _controller: "NewsBundle:Category:edit" }

category_update:
    path:     admin/{id}/update
    defaults: { _controller: "NewsBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    path:     admin/{id}/delete
    defaults: { _controller: "NewsBundle:Category:delete" }
    requirements: { _method: post|delete }
