dispatch:
    path:     admin/
    defaults: { _controller: "NewsBundle:Dispatch:index" }

dispatch_show:
    path:     admin/{id}/show
    defaults: { _controller: "NewsBundle:Dispatch:show" }

dispatch_new:
    path:     admin/new
    defaults: { _controller: "NewsBundle:Dispatch:new" }

dispatch_create:
    path:     admin/create
    defaults: { _controller: "NewsBundle:Dispatch:create" }
    requirements: { _method: post }

dispatch_edit:
    path:     admin/{id}/edit
    defaults: { _controller: "NewsBundle:Dispatch:edit" }

dispatch_update:
    path:     admin/{id}/update
    defaults: { _controller: "NewsBundle:Dispatch:update" }
    requirements: { _method: post|put }

dispatch_delete:
    path:    admin/{id}/delete
    defaults: { _controller: "NewsBundle:Dispatch:delete" }
    requirements: { _method: post|delete }
