dispatch:
    path:     /
    defaults: { _controller: "NewsBundle:Dispatch:index" }

dispatch_show:
    path:     /{id}/show
    defaults: { _controller: "NewsBundle:Dispatch:show" }

dispatch_new:
    path:     /new
    defaults: { _controller: "NewsBundle:Dispatch:new" }

dispatch_create:
    path:     /create
    defaults: { _controller: "NewsBundle:Dispatch:create" }
    requirements: { _method: post }

dispatch_edit:
    path:     /{id}/edit
    defaults: { _controller: "NewsBundle:Dispatch:edit" }

dispatch_update:
    path:     /{id}/update
    defaults: { _controller: "NewsBundle:Dispatch:update" }
    requirements: { _method: post|put }

dispatch_delete:
    path:     /{id}/delete
    defaults: { _controller: "NewsBundle:Dispatch:delete" }
    requirements: { _method: post|delete }
