admin_passwordrecovery:
    path:     /
    defaults: { _controller: "NewsBundle:PasswordRecovery:index" }

admin_passwordrecovery_show:
    path:     /{id}/show
    defaults: { _controller: "NewsBundle:PasswordRecovery:show" }

admin_passwordrecovery_new:
    path:     /new
    defaults: { _controller: "NewsBundle:PasswordRecovery:new" }

admin_passwordrecovery_create:
    path:     /create
    defaults: { _controller: "NewsBundle:PasswordRecovery:create" }
    requirements: { _method: post }

admin_passwordrecovery_edit:
    path:     /{id}/edit
    defaults: { _controller: "NewsBundle:PasswordRecovery:edit" }

admin_passwordrecovery_update:
    path:     /{id}/update
    defaults: { _controller: "NewsBundle:PasswordRecovery:update" }
    requirements: { _method: post|put }

admin_passwordrecovery_delete:
    path:     /{id}/delete
    defaults: { _controller: "NewsBundle:PasswordRecovery:delete" }
    requirements: { _method: post|delete }
