user:
    path:     admin/
    defaults: { _controller: "NewsBundle:User:index" }

user_show:
    path:     admin/{id}/show
    defaults: { _controller: "NewsBundle:User:show" }

user_new:
    path:     admin/new
    defaults: { _controller: "NewsBundle:User:new" }

user_create:
    path:     admin/create
    defaults: { _controller: "NewsBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     admin/{id}/edit
    defaults: { _controller: "NewsBundle:User:edit" }

user_update:
    path:     admin/{id}/update
    defaults: { _controller: "NewsBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     admin/{id}/delete
    defaults: { _controller: "NewsBundle:User:delete" }
    requirements: { _method: post|delete }
