ITR\NewsBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category_name:
            type: string
            length: '255'
#    manyToMany:
#        dispatch:
#            targetEntity: Dispatch
#            inversedBy: category
#            JoinTable:
#                name: category
#                joinColumns:
#                    category_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    dispatch_id:
#                        referencedColumnName: id
    oneToMany:
        news:
            targetEntity: News
            mappedBy: category
        
        dispatches:
            targetEntity: Dispatch
            mappedBy: categories
    
    lifecycleCallbacks: {  }
