ITR\NewsBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\CategoryRepository
    
    oneToMany:
        news:
            targetEntity: News
            mappedBy: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category_name:
            type: string
            length: '255'
    manyToMany:
        dispatch:
            targetEntity: Dispatch
            inversedBy: category
            JoinTable:
                name: category
                joinColumns:
                    category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    dispatch_id:
                        referencedColumnName: id
    
    lifecycleCallbacks: {  }
