ITR\NewsBundle\Entity\Dispatch:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\DispatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    
    manyToMany:
        users:
            targetEntity: User
            mappedBy: dispatchs
    manyToMany:
        category:
            targetEntity: Category
            mappedBy: dispatchs
            
            
            
           
    lifecycleCallbacks: {  }
