ITR\NewsBundle\Entity\Dispatch:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\DispatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category_id:
            type: integer
        user_id:
            type: integer
#    manyToMany:
#        users:
#            targetEntity: User
#            mappedBy: dispatchs
#    manyToMany:
#        category:
#            targetEntity: Category
#            mappedBy: dispatchs
    manyToOne:
        
            categories:
                targetEntity: Category
                inversedBy: dispatch
                joinColumn:
                    name: category_id
                    referencedColumnName: id
            users:
                targetEntity: User
                inversedBy: dispatches
                joinColumn:
                    name: user_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }
