ITR\NewsBundle\Entity\Dispatch:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\DispatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        categoryId:
            type: integer
            column: category_id
    manyToMany:
            user:
                targetEntity: User
                inversedBy: dispatch
                joinTable:
                    name: user
                    referencedColumnName: id    
            
            
            
           
    lifecycleCallbacks: {  }
