ITR\NewsBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\NewsRepository
    indexes:
        title_idx:
            columns: [ title ]
            flags: fulltext
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        author:
            type: string
            length: '255'
        publication_date:
            type: datetime
            length: null
        description:
            type: string
            length: '512'
        content:
            type: text
    manyToOne:
            category:
                targetEntity: Category
                inversedBy: news
                joinColumn:
                    name: category_id
                    referencedColumnName: id
    manyToMany:
          users:
            targetEntity: User
            joinTable:
              name: news_users
              joinColumns:
                news_id:
                  referencedColumnName: id
              inverseJoinColumns:
                user_id:
                  referencedColumnName: id

    lifecycleCallbacks: {  }
