ITR\NewsBundle\Entity\PasswordRecovery:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\PasswordRecoveryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        accessHash:
            type: text
            column: access_hash
        expires:
            type: datetime
    oneToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user
                referencedColumnName: id
    lifecycleCallbacks: {  }
