ITR\NewsBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: ITR\NewsBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user_name:
            type: string
            length: '255'
        user_email:
            type: string
            length: '255'
        user_password:
            type: string
            length: '255'
        user_role:
            type: string
            length: '255'
            options:
                default: ROLE_USER
        user_active:
            type: boolean
            options:
                default: FALSE
        user_hash:
            type: text
    manyToMany:
          category:
            targetEntity: Category
            cascade: ["remove"]
            joinTable:
              name: subscribe
              joinColumns:
                user_id:
                  referencedColumnName: id
              inverseJoinColumns:
                category_id:
                  referencedColumnName: id
                  onDelete: CASCADE
    oneToOne:
        passwordrecovery:
            targetEntity: PasswordRecovery
            mappedBy: user
#    OneToMany:
#        comments:
#             targetEntity: Comment
#             mappeBy: users
    oneToMany:
        comments:
          targetEntity: Comment
          mappedBy: users
    lifecycleCallbacks: {  }
